import { test, expect } from "@playwright/test";

/**
 * Authenticated paid-journey suite (Prompt 18). Requires a TEST Supabase
 * project (never production) via E2E_SUPABASE_TEST=1 plus E2E_TEST_EMAIL /
 * E2E_TEST_PASSWORD of a pre-seeded confirmed user. Skips itself when not
 * configured so CI on the free tier stays green without secrets.
 *
 * Full Stripe checkout/webhook cycles need `stripe listen` and test keys —
 * covered by docs/testing.md manual runbook until a dedicated test env
 * exists (tracked for the go/no-go audit).
 */

const configured =
  process.env.E2E_SUPABASE_TEST === "1" &&
  !!process.env.E2E_TEST_EMAIL &&
  !!process.env.E2E_TEST_PASSWORD;

test.skip(!configured, "E2E test Supabase not configured (E2E_SUPABASE_TEST, E2E_TEST_EMAIL, E2E_TEST_PASSWORD)");

/**
 * Every Playwright test gets a FRESH browser context, so a test that reads an
 * authenticated page must log in itself. Found on the first real run of this
 * suite: two tests were asserting against pages that had silently redirected to
 * /login, and one of them passed anyway because it accepted either branch.
 */
async function login(page: import("@playwright/test").Page) {
  await page.goto("/login");
  await page.fill('input[type="email"]', process.env.E2E_TEST_EMAIL!);
  await page.fill('input[type="password"]', process.env.E2E_TEST_PASSWORD!);
  await page.getByRole("button", { name: /log in/i }).click();
  await page.waitForURL(/dashboard|today|onboarding/, { timeout: 30_000 });

  const checkpoint = page.getByText(/a quick confirmation/i);
  if (await checkpoint.isVisible().catch(() => false)) {
    for (const box of await page.locator('input[type="checkbox"]').all()) {
      await box.check();
    }
    await page.getByRole("button", { name: /confirm and continue/i }).click();
    await expect(checkpoint).toBeHidden();
  }
}

test("login → dashboard → consent state → settings data controls", async ({ page }) => {
  await login(page);

  // Settings shows billing, support and the data controls.
  await page.goto("/settings");
  await expect(page.getByText(/subscription/i).first()).toBeVisible();
  await expect(page.getByText(/support@/i).first()).toBeVisible();
  // The control is labelled "Download my data (JSON)" — asserting on /export/i
  // could never have matched, which is how we know this suite had never run.
  await expect(page.getByRole("button", { name: /download my data/i })).toBeVisible();
  await expect(page.getByRole("button", { name: /delete/i }).first()).toBeVisible();
});

test("pricing reflects trial state for the signed-in user", async ({ page }) => {
  await login(page);
  await page.goto("/pricing");
  // Either trial copy (eligible) or pay-today copy (used) — never both.
  // The CTA is generated by startTrialCta(): "Start N days free".
  const trial = await page.getByText(/start \d+ days? free/i).count();
  const payToday = await page.getByText(/pay today/i).count();
  expect(trial > 0 || payToday > 0).toBe(true);
  expect(trial > 0 && payToday > 0).toBe(false);
});

/**
 * MW-V10-02: whichever arm this seeded user is assigned to, one number must
 * appear on every surface — CTA, footnote, checkout confirmation and billing.
 * The test derives the expected number from the page itself rather than
 * hardcoding 3, so it passes for control and variant users alike and fails on
 * any surface that still names a fixed length.
 */
test("assigned trial length is disclosed identically on pricing and billing", async ({
  page,
}) => {
  await login(page);
  await page.goto("/pricing");
  const cta = page.getByText(/start \d+ days? free/i).first();
  const priorTrial = (await cta.count()) === 0;
  test.skip(priorTrial, "seeded user has already consumed their trial");

  const assigned = ((await cta.innerText()).match(/(\d+)\s+days?/) ?? [])[1];
  expect(assigned).toBeTruthy();

  const pricing = await page.locator("body").innerText();
  // Every trial-length mention on the page agrees with the assigned number.
  for (const match of pricing.matchAll(/(\d+)\s+days?\s+free/gi)) {
    expect(match[1]).toBe(assigned);
  }
  // A concrete cancel-by date is disclosed before Stripe is ever reached.
  await expect(page.getByText(/cancel before/i).first()).toBeVisible();

  await page.goto("/billing");
  await expect(page.getByRole("heading", { name: /^Billing$/ })).toBeVisible();
  const billing = await page.locator("body").innerText();
  for (const match of billing.matchAll(/(\d+)\s+days?\s+free/gi)) {
    expect(match[1]).toBe(assigned);
  }
  expect(billing.toLowerCase()).not.toMatch(/free week|week free/);
});

/**
 * A prior-trial user must never be offered a trial or shown a future cancel-by
 * date — the charge is today. This is the state the billing page previously got
 * wrong: it rendered trial footnote copy for everyone.
 */
test("a user who already used their trial sees pay-today copy only", async ({
  page,
}) => {
  await login(page);
  await page.goto("/billing");
  // Wait for the page itself, not the loading skeleton: MW-V10-07 added a
  // billing skeleton whose text is aria-hidden, so reading innerText straight
  // after goto captured only the app shell and the trial banner.
  await expect(page.getByRole("heading", { name: /^Billing$/ })).toBeVisible();
  const body = await page.locator("body").innerText();

  // This assertion only applies to one state: no active plan AND the one
  // lifetime trial already consumed. A trialing or active account shows the
  // "Trial active" / "Mellowa Premium" panel and no upgrade offer at all —
  // skipping on the absence of a trial CTA was wrong, because a premium user
  // also has no trial CTA. Seed `--state=canceled` with trial_used_at set to
  // exercise this properly.
  const hasActivePlan = /trial active|mellowa premium/i.test(body);
  const offersTrial = /start \d+ days? free/i.test(body);
  test.skip(
    hasActivePlan || offersTrial,
    "seeded user has an active plan or is still trial-eligible"
  );

  expect(body).toMatch(/already used your one Premium trial|pay today/i);
  expect(body).not.toMatch(/cancel before/i);
  expect(body).not.toMatch(/\d+ days? free/i);
});
