import { test, expect } from "@playwright/test";
import {
  E2E_CONFIGURED,
  NOT_CONFIGURED_REASON,
  annotateRetry,
  assertIdentity,
  assertNoBackgroundFailures,
  installFailureGuards,
  login,
  needsState,
  SEEDED_STATE,
  type PageFailures,
} from "./support/harness";

/**
 * Authenticated paid-journey suite (Prompt 18). Requires a TEST Supabase
 * project (never production) via E2E_SUPABASE_TEST=1 plus E2E_TEST_EMAIL /
 * E2E_TEST_PASSWORD of a pre-seeded confirmed user.
 *
 * MW-V11-04: every test now proves which page it is on before asserting what is
 * on it, and fails if the page logged an error, threw, or received an
 * unexpected 4xx/5xx in the background. When the seeded environment is absent
 * the suite is BLOCKED, not passed — CI turns that into a hard error under
 * RC_GATE.
 *
 * Full Stripe checkout/webhook cycles need `stripe listen` and test keys —
 * covered by the docs/testing.md manual runbook until a dedicated test env
 * exists.
 */

test.skip(!E2E_CONFIGURED, NOT_CONFIGURED_REASON);

let failures: PageFailures;

test.beforeEach(({ page }) => {
  failures = installFailureGuards(page);
});

test.afterEach(({}, testInfo) => {
  annotateRetry(testInfo);
  // Only assert cleanliness on a test that otherwise passed: on a failure the
  // console noise is a symptom, and reporting it would bury the real cause.
  if (testInfo.status === testInfo.expectedStatus) {
    assertNoBackgroundFailures(failures);
  }
});

test("login → dashboard → consent state → settings data controls", async ({ page }) => {
  await login(page);

  await page.goto("/settings");
  await assertIdentity(page, {
    route: /\/settings/,
    expect: [/subscription/i, /support@/i],
  });

  // The control is labelled "Download my data (JSON)" — asserting on /export/i
  // could never have matched, which is how we know this suite had never run.
  await expect(page.getByRole("button", { name: /download my data/i })).toBeVisible();
  await expect(page.getByRole("button", { name: /delete/i }).first()).toBeVisible();
});

test("pricing reflects trial state for the signed-in user", async ({ page }) => {
  await login(page);
  await page.goto("/pricing");
  await assertIdentity(page, { route: /\/pricing/ });

  // Either trial copy (eligible) or pay-today copy (used) — never both.
  // The CTA is generated by startTrialCta(): "Start free N-day trial".
  const trial = await page.getByText(/start free \d+-day trial/i).count();
  const payToday = await page.getByText(/pay today/i).count();
  expect(trial > 0 || payToday > 0).toBe(true);
  expect(trial > 0 && payToday > 0).toBe(false);
});

/**
 * MW-V10-02: whichever arm this seeded user is assigned to, one number must
 * appear on every surface — CTA, footnote, checkout confirmation and billing.
 * The test derives the expected number from the page itself rather than
 * hardcoding 3, so it passes for control and variant users alike and fails on
 * any surface that still names a fixed length.
 */
test("assigned trial length is disclosed identically on pricing and billing", async ({
  page,
}) => {
  /*
   * MW-V11-04, two defects in one test.
   *
   * First, the locator matched `/start \d+ days? free/i` — the CTA wording from
   * before MW-V11-01 renamed it to "Start free N-day trial". The count was
   * therefore always 0, `priorTrial` always true, and the test SKIPPED for
   * every user forever while reporting nothing wrong.
   *
   * Second, and worse: the skip condition was read off the page. No seed state
   * produced a trial-eligible user — every one of them wrote a `subscriptions`
   * row — so even with a correct locator this could never have run. The fixture
   * now exists (`--state=trial-eligible`), and the skip is driven by which
   * fixture is loaded rather than by guessing from what is on screen.
   */
  test.skip(SEEDED_STATE !== "trial-eligible", needsState("trial-eligible"));

  await login(page);
  await page.goto("/pricing");
  await assertIdentity(page, { route: /\/pricing/ });

  const cta = page.getByText(/start free \d+-day trial/i).first();
  await expect(
    cta,
    "the trial-eligible fixture is loaded but pricing offers no trial"
  ).toBeVisible();

  const assigned = ((await cta.innerText()).match(/(\d+)-day/) ?? [])[1];
  expect(assigned, "could not read the assigned trial length from the CTA").toBeTruthy();

  const pricing = await page.locator("body").innerText();
  // Every trial-length mention on the page agrees with the assigned number, in
  // both the noun form ("3 days free") and the adjective form ("3-day trial").
  for (const match of pricing.matchAll(/(\d+)\s+days?\s+free/gi)) {
    expect(match[1]).toBe(assigned);
  }
  for (const match of pricing.matchAll(/(\d+)-day\s+trial/gi)) {
    expect(match[1]).toBe(assigned);
  }
  // A concrete cancel-by date is disclosed before Stripe is ever reached.
  await expect(page.getByText(/cancel before/i).first()).toBeVisible();

  await page.goto("/billing");
  await assertIdentity(page, { route: /\/billing/, heading: /^Billing$/ });
  const billing = await page.locator("body").innerText();
  for (const match of billing.matchAll(/(\d+)\s+days?\s+free/gi)) {
    expect(match[1]).toBe(assigned);
  }
  for (const match of billing.matchAll(/(\d+)-day\s+trial/gi)) {
    expect(match[1]).toBe(assigned);
  }
  expect(billing.toLowerCase()).not.toMatch(/free week|week free/);
  // MW-V11-01: the ungrammatical form must not reach an authenticated surface.
  expect(billing).not.toMatch(/\ba \d+ days\b/i);
});

/**
 * A prior-trial user must never be offered a trial or shown a future cancel-by
 * date — the charge is today. This is the state the billing page previously got
 * wrong: it rendered trial footnote copy for everyone.
 */
test("a user who already used their trial sees pay-today copy only", async ({
  page,
}) => {
  /*
   * This assertion applies to exactly one state: no active plan AND the one
   * lifetime trial already consumed. The old version inferred that state from
   * the page and skipped otherwise, which meant it also skipped for a premium
   * user, for a trialing user, and for a broken seed — indistinguishably. The
   * v10 note on this test even said what was needed ("seed --state=canceled
   * with trial_used_at set"); no such fixture existed until MW-V11-04 added it.
   */
  test.skip(SEEDED_STATE !== "trial-used", needsState("trial-used"));

  await login(page);
  await page.goto("/billing");
  // Wait for the page itself, not the loading skeleton: MW-V10-07 added a
  // billing skeleton whose text is aria-hidden, so reading innerText straight
  // after goto captured only the app shell and the trial banner.
  await assertIdentity(page, { route: /\/billing/, heading: /^Billing$/ });
  const body = await page.locator("body").innerText();

  // The fixture is loaded, so these are assertions now, not skip conditions.
  expect(body, "trial-used fixture still shows an active plan").not.toMatch(
    /trial active|mellowa premium/i
  );
  expect(body, "trial-used fixture is still being offered a trial").not.toMatch(
    /start free \d+-day trial/i
  );

  expect(body).toMatch(/already used your one Premium trial|pay today/i);
  expect(body).not.toMatch(/cancel before/i);
  expect(body).not.toMatch(/\d+ days? free/i);
  expect(body).not.toMatch(/\d+-day trial/i);
});

/**
 * MW-V12-02: sign out ends the session from the account hub.
 *
 * State-independent — the SignOutButton lives on /you and behaves the same for
 * any subscription state, so this runs under whatever fixture is loaded.
 */
test("sign out ends the session and returns to login", async ({ page }) => {
  await login(page);
  await page.goto("/you");
  await assertIdentity(page, { route: /\/you/ });

  // The /you page renders its own Sign out button in #main, and the persistent
  // sidebar renders another — so an unscoped role query matches two elements.
  // Click the one on the page under test (the #main SignOutButton).
  const signOut = page.locator("#main").getByRole("button", { name: /^Sign out$/ });
  await signOut.waitFor({ state: "visible" });
  // On a slow CI worker the SSR button is clickable before React attaches its
  // onClick, so a single click can be lost and the navigation never fires. Retry
  // the click until the redirect actually happens (each attempt is cheap).
  await expect(async () => {
    await signOut.click();
    await page.waitForURL(/\/login/, { timeout: 5_000 });
  }).toPass({ timeout: 30_000 });
  expect(page.url(), "sign out did not return to /login").toMatch(/\/login/);

  // The session is really gone: an authenticated route bounces back to login
  // rather than rendering from a stale cache.
  await page.goto("/today");
  await expect(page).toHaveURL(/\/login/);
});

/**
 * MW-V12-02: an expired/absent session must redirect an authenticated route to
 * login, not render a partial page. This is the failure assertIdentity was
 * built to catch — a test that only checks for an element's absence passes on
 * the login page forever.
 */
test("an expired session redirects to login instead of rendering", async ({ page }) => {
  await login(page);
  // Drop every cookie: the server session is now gone from the browser's view.
  await page.context().clearCookies();
  await page.goto("/today");
  await expect(page).toHaveURL(/\/login/);
});

/**
 * MW-V12-02: a user who has consumed their one free sample must be told Premium
 * is needed to generate again — not offered a second sample. Gated on the
 * `sample-used` fixture, following the same fixture-driven skip contract as the
 * trial tests above (never a guess read off the page).
 */
test("sample-used check-in points to Premium, not another free sample", async ({
  page,
}) => {
  test.skip(SEEDED_STATE !== "sample-used", needsState("sample-used"));

  await login(page);
  await page.goto("/check-in");
  await assertIdentity(page, { route: /\/check-in/ });

  // Retry the read: check-in is a server component behind a Suspense boundary
  // (check-in/loading.tsx is a text-free skeleton), so a one-shot innerText read
  // races the streamed content on a higher-latency database and sees only the
  // nav shell. A retrying assertion waits for the gate copy to actually arrive.
  await expect(
    page.locator("body"),
    "sample-used fixture is not showing the consumed-sample gate"
  ).toContainText(/used your free sample plan/i);
  const body = await page.locator("body").innerText();
  expect(body, "a consumed sample must not offer another free sample").not.toMatch(
    /creates your one free sample plan/i
  );
  // One route onward to Premium, via Billing.
  await expect(page.getByRole("link", { name: /^Billing$/ })).toBeVisible();
});
