import { serverEnv } from "@/lib/env";
import { readLegalConfig } from "@/lib/legal/config";
import {
  trialLengthAdjective,
  trialLengthLabel,
} from "@/lib/stripe/trial-experiment";

/**
 * Lifecycle email templates (Content Elevation v6, Prompt 17).
 *
 * Precise, premium and non-sensitive. Transactional subjects carry no emoji;
 * no email includes mood, stress, meals, allergies, journal or plan content.
 * Billing emails render server-derived plan, exact price and dates when the
 * caller provides them, and fall back to a truthful sentence (pointing to
 * Billing) rather than inventing a number. Plain-text alternatives are
 * generated by the delivery layer (htmlToText).
 */

const BRAND = "#6D8C7D";
const TEXT = "#1F2937";
const MUTED = "#6B7280";

export interface Email {
  subject: string;
  html: string;
}

/** Server-derived billing facts. All three are needed to state an exact charge. */
export interface BillingFacts {
  /** Human plan label, e.g. "Monthly plan". */
  plan?: string;
  /** Already-formatted price with currency, e.g. "€6.99". */
  price?: string;
  /** Already-formatted date, e.g. "17 August 2026". */
  date?: string;
}

function hasExact(f: BillingFacts): f is Required<BillingFacts> {
  return Boolean(f.plan && f.price && f.date);
}

/** Preheader = the preview line most inboxes show next to the subject. */
function shell(bodyHtml: string, preheader: string): string {
  return `<!doctype html><html lang="en"><body style="margin:0;background:#FAF7F2;padding:24px;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:${TEXT};">
  <span style="display:none!important;visibility:hidden;opacity:0;height:0;width:0;overflow:hidden;">${preheader}</span>
  <div style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:16px;padding:32px;">
    <div style="font-size:20px;font-weight:600;letter-spacing:-0.02em;margin-bottom:20px;">Mellowa</div>
    ${bodyHtml}
    <hr style="border:none;border-top:1px solid #EDE9E2;margin:28px 0 16px;" />
    <p style="font-size:12px;color:${MUTED};line-height:1.6;margin:0;">
      Mellowa is a wellbeing app — not medical care, therapy or emergency support.
      If you're in crisis, please contact your local emergency services.
    </p>
    <p style="font-size:12px;color:${MUTED};line-height:1.6;margin:8px 0 0;">
      Questions? Contact <a href="mailto:${readLegalConfig().supportEmail}" style="color:${BRAND};">${readLegalConfig().supportEmail}</a>.
      This inbox is not monitored for emergencies.
    </p>
  </div>
</body></html>`;
}

function button(label: string, href: string): string {
  // role/aria make the link read as a button to assistive tech.
  return `<a href="${href}" role="button" style="display:inline-block;background:${BRAND};color:#ffffff;text-decoration:none;padding:12px 20px;border-radius:12px;font-weight:600;font-size:15px;">${label}</a>`;
}

function secondaryLink(label: string, href: string): string {
  return `<a href="${href}" style="color:${BRAND};font-size:14px;">${label}</a>`;
}

function p(text: string): string {
  return `<p style="font-size:16px;line-height:1.6;">${text}</p>`;
}

const appUrl = () => serverEnv.appUrl;

/** Confirm-email (available for Supabase custom template parity / tests). */
export function verifyEmail(confirmUrl: string): Email {
  return {
    subject: "Confirm your Mellowa account",
    html: shell(
      `${p("Confirm your email to continue setting up Mellowa.")}
       <p style="margin:24px 0;">${button("Confirm email", confirmUrl)}</p>`,
      "One step before your free sample day."
    ),
  };
}

/** Welcome / setup — sent after verification, before onboarding. */
export function welcomeEmail(): Email {
  return {
    subject: "Your Mellowa setup is ready",
    html: shell(
      `${p("Welcome to Mellowa.")}
       ${p(
         "Mellowa turns your available energy, time and schedule into one realistic day plan. Start with a short setup, then create your free sample day."
       )}
       <p style="margin:24px 0;">${button("Set up Mellowa", `${appUrl()}/onboarding`)}</p>`,
      "Set the basics once, then keep daily check-ins short."
    ),
  };
}

/** Sample-ready — sent after the first free sample plan exists. */
export function sampleReadyEmail(): Email {
  return {
    subject: "Your sample day is ready",
    html: shell(
      `${p("Your free sample day is ready to view.")}
       <p style="margin:24px 0;">${button("See today's plan", `${appUrl()}/today`)}</p>`,
      "A realistic starting point—not a list you have to finish."
    ),
  };
}

/**
 * MW-V10-02: `trialDays` is the length Stripe actually granted, so a cohort on
 * a different trial length never receives the other arm's number. When it is
 * unknown the copy stays length-neutral instead of guessing.
 */
export function trialStartedEmail(
  facts: BillingFacts = {},
  trialDays: number | null = null
): Email {
  const length = trialDays === null ? null : trialLengthLabel(trialDays);
  const adjective = trialLengthAdjective(trialDays);
  const body = hasExact(facts)
    ? p(
        `Your ${facts.plan} trial is active. You'll be charged ${facts.price} on ${facts.date} unless you cancel before then.`
      )
    : p(
        "Your Mellowa trial is active. You'll be charged when the trial ends unless you cancel before then. Your exact price and date are on the billing page."
      );
  return {
    subject: adjective
      ? `Your ${adjective} Mellowa trial has started.`
      : "Your Mellowa trial has started.",
    html: shell(
      `${body}
       <p style="margin:24px 0;">${button("Open Mellowa", `${appUrl()}/today`)}</p>
       <p style="margin:0;">${secondaryLink("Manage billing", `${appUrl()}/billing`)}</p>`,
      length
        ? `Full access for ${length}. Cancel anytime before it renews.`
        : "Full access for the whole trial. Cancel anytime before it renews."
    ),
  };
}

/**
 * MW-V11: the subject states WHEN the trial ends, computed from the real
 * trial_end in the user's own timezone by the caller. The old copy hard-coded
 * "ends tomorrow" for everyone the daily cron caught within 24h — so a trial
 * ending later today, or one whose mail landed after a delivery lag, arrived
 * announcing a day that had already passed. `daysUntilEnd` is 0 for today,
 * 1 for tomorrow, N for further out; null keeps the length-neutral wording.
 */
function trialEndingSubject(daysUntilEnd: number | null): string {
  if (daysUntilEnd === null) return "Your Mellowa trial ends soon";
  if (daysUntilEnd <= 0) return "Your Mellowa trial ends today";
  if (daysUntilEnd === 1) return "Your Mellowa trial ends tomorrow";
  return `Your Mellowa trial ends in ${daysUntilEnd} days`;
}

export function trialEndingEmail(
  facts: BillingFacts = {},
  daysUntilEnd: number | null = null
): Email {
  const body = hasExact(facts)
    ? p(
        `Your ${facts.plan} trial ends on ${facts.date}. You'll be charged ${facts.price} on that date unless you cancel first.`
      )
    : p(
        "Your Mellowa trial ends soon. You'll be charged on that date unless you cancel first — see billing for the exact price and date."
      );
  return {
    subject: trialEndingSubject(daysUntilEnd),
    html: shell(
      `${body}
       <p style="margin:24px 0;">${button("Manage membership", `${appUrl()}/billing`)}</p>`,
      "Continue automatically, or cancel before you're charged."
    ),
  };
}

/** Trial converted to paid — confirmation, no wellbeing content. */
export function trialEndedEmail(): Email {
  return {
    subject: "You're now on Mellowa Premium",
    html: shell(
      `${p("Your trial has ended and your subscription is active.")}
       ${p("You can review or change your plan anytime from Billing.")}
       <p style="margin:24px 0;">${button("Open Mellowa", `${appUrl()}/today`)}</p>`,
      "Your subscription is active."
    ),
  };
}

export function canceledEmail(facts: BillingFacts = {}): Email {
  const until = facts.date
    ? `Premium remains available until ${facts.date}. You won't be charged again.`
    : "Premium remains available until the end of your current period. You won't be charged again.";
  return {
    subject: "Your Mellowa plan is canceled",
    html: shell(
      `${p(until)}
       <p style="margin:24px 0;">${button("View membership", `${appUrl()}/billing`)}</p>`,
      "You won't be charged again."
    ),
  };
}

export function paymentFailedEmail(facts: BillingFacts = {}): Email {
  const amount = facts.price
    ? `${facts.price}${facts.plan ? ` for ${facts.plan}` : ""}`
    : null;
  const body = amount
    ? p(
        `We couldn't process ${amount}. Saved plans remain available. Update your payment method to keep creating new Premium plans.`
      )
    : p(
        "We couldn't process your latest payment. Saved plans remain available. Update your payment method to keep creating new Premium plans."
      );
  return {
    subject: "Your Mellowa payment needs attention",
    html: shell(
      `${body}
       <p style="margin:24px 0;">${button("Update payment method", `${appUrl()}/billing`)}</p>`,
      "Update your payment method to keep creating new plans."
    ),
  };
}

/** Payment recovered — dunning success confirmation (Launch v6, Prompt 19). */
export function paymentRecoveredEmail(): Email {
  return {
    subject: "Your Mellowa payment went through",
    html: shell(
      `${p("Your latest payment was processed and your subscription is active again. Nothing else to do.")}
       <p style="margin:24px 0;">${button("Open Mellowa", `${appUrl()}/today`)}</p>`,
      "Your subscription is active again."
    ),
  };
}

/** Account deletion confirmed — sent before the auth user is removed. */
export function accountDeletedEmail(): Email {
  return {
    subject: "Your Mellowa account has been deleted",
    html: shell(
      `${p("Your account and its data have been deleted as requested. Any active subscription was canceled — you won't be charged again.")}
       ${p("If this wasn't you, contact support right away.")}`,
      "Your data has been removed. You won't be charged again."
    ),
  };
}

/**
 * One-time onboarding nudge — sent once if setup wasn't finished within a day.
 * Optional category: never repeated, suppressed the moment a profile exists.
 */
export function onboardingNudgeEmail(optOutUrl?: string | null): Email {
  return {
    subject: "Finish your Mellowa setup",
    html: shell(
      `${p("You created a Mellowa account but haven't finished setup. It takes about two minutes, then your free sample day is ready to create.")}
       <p style="margin:24px 0;">${button("Finish setup", `${appUrl()}/onboarding`)}</p>
       ${p(
         `This is the only reminder we'll send about setup.${
           optOutUrl
             ? ` <a href="${optOutUrl}" style="color:#6B7280">Turn reminder emails off</a>.`
             : ""
         }`
       )}`,
      "Two minutes of setup, then your free sample day."
    ),
  };
}
